### ISSUE TITLE
Remove secret key.

### ISSUE THREAD

**Issue by ajackson** [wavefrontHQ/demo-app#15]
We shouldn't hardcode this value.

https://github.com/wavefrontHQ/demo-app/blob/47eac16af8b4eb7b79c9b65c83b981199b9f39bb/warehouse/warehouse/settings.py#L34

**Comment by scrogatl** [comment]
This is an internal key used for the python portion of the app... it's not really secret.. and this app is intended for demo use only and should NEVER be used in production env
